function output = ERVG(N)  
    
    lambda = 1; 
   
    R = rand(1, N); 
    
    X = (-1 / lambda) .* log(1 - R); 
    
    %Normalized outlier value generated by ERVG
    X_normalized = 1 - exp(-lambda .* X);
    X_normalized(X_normalized >= 1.0) = 0.999999;
    output = X_normalized;
end